from __future__ import annotations

from collections import Counter
from typing import Any


def build_card_status_rows(normalized_cards: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for card in normalized_cards:
        abilities = [ability for ability in card.get("abilities", []) if isinstance(ability, dict)]
        status_counts = Counter(str(ability.get("status", "")) for ability in abilities)
        timings = sorted({str(ability.get("timing")) for ability in abilities if ability.get("timing")})
        effects = sorted(
            {
                str(step.get("effect"))
                for ability in abilities
                for step in list(ability.get("cost_steps", [])) + list(ability.get("effect_steps", []))
                if isinstance(step, dict) and step.get("effect")
            }
        )
        rows.append(
            {
                "card_no": card.get("card_no", ""),
                "card_name": card.get("name", ""),
                "category": card.get("category", ""),
                "color": card.get("color", ""),
                "ability_count": len(abilities),
                "supported": status_counts.get("supported", 0),
                "deferred": status_counts.get("deferred", 0),
                "unsupported": status_counts.get("unsupported", 0),
                "implementation_status": _implementation_status(status_counts, len(abilities)),
                "timings": timings,
                "effects": effects,
            }
        )
    return rows


def build_card_status_markdown(normalized: dict[str, Any], report: dict[str, Any]) -> str:
    rows = build_card_status_rows(list(normalized.get("cards") or []))
    summary_counts = Counter(row["implementation_status"] for row in rows)
    lines = [
        "# Card Implementation Status",
        "",
        "This file is generated from `carddata/generated/cards.normalized.json` and `carddata/generated/cardpool_report.json`.",
        "Do not edit this file by hand; regenerate it through the cardpool CLI.",
        "",
        "## Summary",
        "",
        f"- Cards: {len(rows)}",
        f"- Supported abilities: {report.get('supported_ability_count', 0)}",
        f"- Status counts: {_format_counts(report.get('status_counts') or {})}",
        f"- Card implementation: {_format_counts(dict(sorted(summary_counts.items())))}",
        "",
        "## Cards",
        "",
        "| card_no | card_name | category | abilities | status | timings | effects |",
        "| --- | --- | --- | ---: | --- | --- | --- |",
    ]
    for row in rows:
        ability_text = f"{row['supported']}/{row['deferred']}/{row['unsupported']}"
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{_escape_md(row['card_no'])}`",
                    _escape_md(row["card_name"]),
                    _escape_md(row["category"]),
                    ability_text,
                    _escape_md(row["implementation_status"]),
                    _escape_md(", ".join(row["timings"])),
                    _escape_md(", ".join(row["effects"])),
                ]
            )
            + " |"
        )
    lines.append("")
    lines.append("Ability count format is `supported/deferred/unsupported`.")
    return "\n".join(lines)


def _implementation_status(status_counts: Counter[str], ability_count: int) -> str:
    if ability_count == 0:
        return "no_ability"
    supported = status_counts.get("supported", 0)
    if supported == ability_count:
        return "supported"
    if supported > 0:
        return "partial"
    if status_counts.get("deferred", 0) > 0:
        return "deferred"
    return "unsupported"


def _format_counts(counts: dict[str, Any]) -> str:
    if not counts:
        return "-"
    return ", ".join(f"{key}={value}" for key, value in counts.items())


def _escape_md(value: Any) -> str:
    return str(value).replace("|", "\\|")
