from __future__ import annotations

from pathlib import Path
from typing import Any

from tojs_reborn.engine.state import CardDefinition


def scenario_catalog_entry(
    scenario_name: str,
    replay_record: dict[str, Any],
    *,
    replay_path: str,
    card_catalog: dict[str, CardDefinition],
) -> dict[str, Any]:
    card_nos = _collect_card_nos(replay_record)
    return {
        "scenario": scenario_name,
        "version": _scenario_version(scenario_name),
        "replay": replay_path,
        "event_count": len(replay_record.get("events") or []),
        "card_nos": card_nos,
        "cards": [_format_card(card_no, card_catalog) for card_no in card_nos],
    }


def build_scenario_catalog_markdown(entries: list[dict[str, Any]]) -> str:
    lines = [
        "# Scenario Catalog",
        "",
        "This file is generated by `python -m tojs_reborn.io.scenario_cli --scenario all --catalog-markdown docs/scenario_catalog.md`.",
        "Do not edit this file by hand; regenerate it after scenario changes.",
        "",
        f"- Scenarios: {len(entries)}",
        "",
        "| scenario | version | events | cards | replay |",
        "| --- | --- | ---: | --- | --- |",
    ]
    for entry in sorted(entries, key=lambda item: str(item.get("scenario", ""))):
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{_escape_md(entry.get('scenario', ''))}`",
                    _escape_md(entry.get("version", "")),
                    str(entry.get("event_count", 0)),
                    _escape_md(", ".join(entry.get("cards") or [])),
                    f"`{_escape_md(_relative_path(entry.get('replay', '')))}`",
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def _collect_card_nos(replay_record: dict[str, Any]) -> list[str]:
    card_nos: set[str] = set()
    for state_key in ("initial_state", "final_state"):
        state = replay_record.get(state_key)
        if not isinstance(state, dict):
            continue
        for card in (state.get("card_instances") or {}).values():
            if isinstance(card, dict) and isinstance(card.get("card_no"), str):
                card_nos.add(card["card_no"])
    return sorted(card_nos)


def _scenario_version(scenario_name: str) -> str:
    if scenario_name.startswith("v9_"):
        return "v9"
    if scenario_name.startswith("v8_"):
        return "v8"
    return "v7"


def _format_card(card_no: str, card_catalog: dict[str, CardDefinition]) -> str:
    card = card_catalog.get(card_no)
    if card is None:
        return card_no
    return f"{card.name}({card_no})"


def _relative_path(path: Any) -> str:
    if not isinstance(path, str):
        return ""
    try:
        return Path(path).as_posix()
    except TypeError:
        return path


def _escape_md(value: Any) -> str:
    return str(value).replace("|", "\\|")
